language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra
install: "./gradlew assemble"
script: "./gradlew check"
