language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  - platform-tools
  - extra
install: "./gradlew assemble"
script: "./gradlew check"
